### ISSUE TITLE
0.49.3版本后GroupTileLayer的layers参数为GroupTileLayer时错误

### ISSUE THREAD

**Issue by ok958726** [maptalks/maptalks.js#1566]
**maptalks's version and what browser you use?**
----
浏览器使用 chrome，maptalks版本分别使用0.49.3以及1.0.0-beta.7

**Issue description**
----
在0.49.3版本以前，GroupTileLayer可以作为GroupTileLayer的layers参数传入。但是切换你到1.0.0-beta.7版本后，报错：
Uncaught TypeError: Cannot read properties of undefined (reading 'isTileCachedOrLoading')
    at TileLayer._splitNode (maptalks.es.js:28768:1)
    at TileLayer._getPyramidTiles (maptalks.es.js:28721:1)
    at TileLayer.getTiles (maptalks.es.js:28509:1)
    at GroupTileLayer.getTiles (maptalks.es.js:29661:1)
    at GroupTileLayer.getTiles (maptalks.es.js:29661:1)
    at TileLayerGLRenderer.draw (maptalks.es.js:33616:1)
    at TileLayerGLRenderer._drawAndRecord (maptalks.es.js:7308:1)
    at TileLayerGLRenderer._tryToDraw (maptalks.es.js:7297:1)
    at TileLayerGLRenderer.checkAndDraw (maptalks.es.js:6815:1)
    at TileLayerGLRenderer.render (maptalks.es.js:6785:1)

使用场景是需要在maptalks自带的LayerSwitcher中切换不同的地图作为底图，每一个地图项又由几个tileLayer组合而成。
不知道这样使用是不是不太合理？

**Please provide a reproduction URL (on any jsfiddle like site)**
----
切换aptalks版本可看到错误：
https://codepen.io/ok958726/pen/oNGreME

**Comment by fuzhenn** [comment]
这个用法是合理的，是我们的bug。
已经解决并添加了测试用例，发布为 1.0.0-beta.10 版
https://github.com/maptalks/maptalks.js/pull/1569
