### ISSUE TITLE
请问有可用的Vue3的示例嘛？

### ISSUE THREAD

**Issue by Lumysia** [maptalks/maptalks.js#1658]
**maptalks's version and what browser you use?**
----
1.0.0-rc.4

**Issue description**
----
请问有可用的Vue3的示例嘛？

### 安装
- `yarn add maptalks`

### 代码
```vue
<template>
    <div class="test">
        <div id="map" class="container"></div>
    </div>
</template>

<script setup>
import * as maptalks from "maptalks";

var map = new maptalks.Map("map", {
    center: [-0.113049, 51.498568],
    zoom: 14,
    baseLayer: new maptalks.TileLayer("base", {
        urlTemplate:
            "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
        subdomains: ["a", "b", "c", "d"],
        attribution:
            '&copy; <a href="http://osm.org">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/">CARTO</a>',
    }),
});
</script>
```

### 浏览器报错
```text
[vite] connecting... client.ts:16:8
[Vue warn]: Unhandled error during execution of setup function 
  at <MapTalkMap key=0 > 
  at <Map onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:38:16
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <MapTalkMap key=0 > 
  at <Map onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:38:16
Uncaught (in promise) Error: Invalid container when creating map: 'map'
    _initContainer maptalks.es-bundler.js:13773
    Map2 maptalks.es-bundler.js:12678
    setup mapTalkMap.vue:10
    callWithErrorHandling runtime-core.esm-bundler.js:155
    setupStatefulComponent runtime-core.esm-bundler.js:7056
    setupComponent runtime-core.esm-bundler.js:7012
    mountComponent runtime-core.esm-bundler.js:4922
    processComponent runtime-core.esm-bundler.js:4897
    patch runtime-core.esm-bundler.js:4489
    mountChildren runtime-core.esm-bundler.js:4685
    processFragment runtime-core.esm-bundler.js:4856
    patch runtime-core.esm-bundler.js:4482
    componentUpdateFn runtime-core.esm-bundler.js:5037
    run reactivity.esm-bundler.js:167
    setupRenderEffect runtime-core.esm-bundler.js:5156
    mountComponent runtime-core.esm-bundler.js:4939
    processComponent runtime-core.esm-bundler.js:4897
    patch runtime-core.esm-bundler.js:4489
    componentUpdateFn runtime-core.esm-bundler.js:5107
    run reactivity.esm-bundler.js:167
    callWithErrorHandling runtime-core.esm-bundler.js:155
    flushJobs runtime-core.esm-bundler.js:394
    promise callback*queueFlush runtime-core.esm-bundler.js:285
    queueCb runtime-core.esm-bundler.js:307
    queuePostFlushCb runtime-core.esm-bundler.js:313
    queueEffectWithSuspense runtime-core.esm-bundler.js:1577
    scheduler runtime-core.esm-bundler.js:1801
    triggerEffects reactivity.esm-bundler.js:359
    triggerRefValue reactivity.esm-bundler.js:957
    effect reactivity.esm-bundler.js:1088
    triggerEffects reactivity.esm-bundler.js:359
    triggerRefValue reactivity.esm-bundler.js:957
    effect reactivity.esm-bundler.js:1088
    triggerEffects reactivity.esm-bundler.js:359
    triggerRefValue reactivity.esm-bundler.js:957
    set value reactivity.esm-bundler.js:1001
    finalizeNavigation vue-router.esm-bundler.js:3194
    pushWithRedirect vue-router.esm-bundler.js:3067
    promise callback*pushWithRedirect vue-router.esm-bundler.js:3038
    push vue-router.esm-bundler.js:2966
    install vue-router.esm-bundler.js:3380
    use runtime-core.esm-bundler.js:3808
    <anonymous> main.js:19
maptalks.es-bundler.js:13773:14
[vite] connected. client.ts:53:14
源映射错误：Error: request failed with status 404
源 URL：http://localhost:3000/#/Map
源映射 URL：bootstrap.min.css.map
```

-----

> 真的很抱歉问这么愚蠢的问题，但是真的没找到可用的Demo......

**Comment by fuzhenn** [comment]
这里有一篇相关文章：
https://juejin.cn/post/7030361550007304228

**Comment by Lumysia** [comment]
> 这里有一篇相关文章：
> https://juejin.cn/post/7030361550007304228

感谢您的回复，这篇文章看过了但是结构实在是太混乱所以没能按它的介绍做出相同的东西
