### ISSUE TITLE
sveltekit, importing maptalks: Internal server error: Image is not defined

### ISSUE THREAD

**Issue by m1027** [maptalks/maptalks.js#1920]
**maptalks's version and what browser you use?**
----
firefox-111
maptalks: 1.0.0-rc.18

cat package.json
```
{
	"name": "my-app",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch"
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"vite": "^4.2.0"
	},
	"type": "module",
	"dependencies": {
		"maptalks": "^1.0.0-rc.18"
	}
}
```

**Issue description**
----
When I try to import maptalks in sveltekit I get the error ```Internal server error: Image is not defined``` when starting ```npm run dev```. This can be reproduces with a clean sveltekit demo app, only by adding the import line (see steps below).

Maybe I am missing something trivial.

FYI: The stand-alone examples from maptalks without embedding into sveltekit work normally here.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

This is how to reproduce:
```
- mkdir tmp; cd tmp
- npm create svelte@latest my-app
- select skeleton project
- select typescript
- select no additional options
- cd my-app
- npm install
- npm run dev -- --open
- edit and insert into src/routes/+page.svelte:
  <script lang="ts">
  import { maptalks } from 'maptalks';
  </script>
- npm install maptalks
- npm run dev -- --open

output:

5:07:55 PM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "maptalks"

Internal server error: Image is not defined
      at /home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:36256:21
      at /home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:7:66
      at Object.<anonymous> (/home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:10:2)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
ReferenceError: Image is not defined
    at /home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:36256:21
    at /home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:7:66
    at Object.<anonymous> (/home/user/tmp/sveltekit/my-app/node_modules/maptalks/dist/maptalks.js:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
5:07:55 PM [vite-plugin-svelte] ssr compile in progress ...
5:07:56 PM [vite-plugin-svelte] ssr compile done.
package files     time     avg
my-app      4   76.7ms  19.2ms
```

**Comment by m1027** [comment]
Solution to use maptalks in svelte / sveltekit:

- Disable SSR by adding a file `+page.server.ts` with `export const ssr = false;`.
- Instantiate the map inside an `onMount()` function.
- Import: `import * as maptalks from 'maptalks';`
